const MOCK_DATA = [
  // --- 북문 (North Gate) ---
  {
    id: 1,
    name: "취향",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식", "중식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#원픽", "#청양크림파스타", "#분위기 좋음"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Chinese", "Fusion"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#MyPick", "#SpicyCreamPasta", "#GoodVibes"],
    web_link: "https://map.naver.com/p/entry/place/1956104979?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\1취향.jpg",
  },
  {
    id: 2,
    name: "와비사비",
    kor_loc: "북문",
    kor_food: ["일식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#투픽", "#명란크림우동", "#신상술집"],
    eng_loc: "North Gate",
    eng_food: ["Japanese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#2ndPick", "#PollackRoeCreamUdon", "#NewPub"],
    web_link: "https://map.naver.com/p/entry/place/2052226947?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\2와비사비.jpg",
  },
  {
    id: 3,
    name: "한라맥주",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#학과행사하기좋음", "#로제찜닭", "#감귤모자", "#넓고좋음"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Fusion"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: [
      "#GoodForEvents",
      "#RoseSteamedChicken",
      "#TangerineHat",
      "#Spacious",
    ],
    web_link: "https://map.naver.com/p/entry/place/1342206450?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\3한라맥주.jpg",
  },
  {
    id: 4,
    name: "사군자민속촌",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [
      "#낙지볶음에면은한번에섞지말고조금씩섞어먹으세요",
      "#막걸리굿",
      "#빈대떡존맛",
    ],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [
      "#MixNoodlesLittleByLittle",
      "#GoodRiceWine",
      "#TastyMungBeanPancake",
    ],
    web_link: "https://map.naver.com/p/entry/place/335604916?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\4사군자민속촌.jpg",
  },
  {
    id: 5,
    name: "데얼스",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "중식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#어두운 분위기…?", "#기본안주치즈과자", "#떠먹는 피자"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Chinese", "Fusion"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#DarkAtmosphere", "#FreeCheeseSnacks", "#SpoonPizza"],
    web_link: "https://map.naver.com/p/entry/place/36175140?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\5데얼스.jpg",
  },
  {
    id: 6,
    name: "오뉴월",
    kor_loc: "북문",
    kor_food: ["일식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기 좋음", "#이자카야느낌"],
    eng_loc: "North Gate",
    eng_food: ["Japanese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes", "#IzakayaStyle"],
    web_link: "https://map.naver.com/p/entry/place/1638911029?c=15.00,0,0,0,adh",
    img_url: "src\\constant\\img\\a_Noth\\6오뉴월.jpg",
  },
  {
    id: 7,
    name: "사심",
    kor_loc: "북문",
    kor_food: ["일식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기 좋음", "#이자카야 느낌", "#야끼소바"],
    eng_loc: "North Gate",
    eng_food: ["Japanese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes", "#IzakayaStyle", "#Yakisoba"],
    web_link: "https://map.naver.com/p/entry/place/1468664455?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\7사심.jpg",
  },
  {
    id: 8,
    name: "희희",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#과 행사하기 좋음", "#샤브샤브", "#기본안주 맛있음"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Fusion"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#GoodForEvents", "#ShabuShabu", "#TastyFreeSnacks"],
    web_link: "https://map.naver.com/p/entry/place/1555072378?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\8희희.jpg",
  },
  {
    id: 9,
    name: "구구포차",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#야구보기 좋음", "#과 행사하기 좋음", "#닭요리 위주"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#GoodForBaseball", "#GoodForEvents", "#ChickenDishes"],
    web_link: "https://map.naver.com/p/entry/place/1234772562?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\9구구포차.jpg",
  },
  {
    id: 10,
    name: "정든밤",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#안주가 다 맛있는 편", "#10인 단체도 가능", "#분위기굿"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#TastyDishes", "#GroupsOf10OK", "#GoodVibes"],
    web_link: "https://map.naver.com/p/entry/place/1519176028?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\10정든밤.jpg",
  },
  {
    id: 11,
    name: "정선생",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#고구마크림막걸리", "#분위기굿"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#SweetPotatoCreamRiceWine", "#GoodVibes"],
    web_link: "https://map.naver.com/p/entry/place/31663892?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\11정선생.jpg",
  },
  {
    id: 12,
    name: "큐브",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "과팅"],
    kor_hashtag: ["#룸술집"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Group Dating"],
    eng_hashtag: ["#PrivateRoom"],
    web_link: "https://map.naver.com/p/entry/place/1295630060?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\12큐브2.jpg",
  },
  {
    id: 13,
    name: "청춘",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "과팅"],
    kor_hashtag: ["#룸술집"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Group Dating"],
    eng_hashtag: ["#PrivateRoom"],
    web_link: "https://map.naver.com/p/entry/place/1943296021?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\13청춘1.jpg",
  },
  {
    id: 14,
    name: "사랑과평화",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#계수작반반양념구이", "#행사적합", "#스크린이랑마이크있음"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Fusion"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#HalfHalfSeasonedGrill", "#GoodForEvents", "#ScreenAndMic"],
    web_link: "https://map.naver.com/p/entry/place/1667063210?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\14사랑과 평화.jpg",
  },
  {
    id: 15,
    name: "홍등연화",
    kor_loc: "북문",
    kor_food: ["한식", "일식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#지하", "#행사적합"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Japanese", "Fusion"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#Basement", "#GoodForEvents"],
    web_link: "https://map.naver.com/p/entry/place/1346947035?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\15홍등연화.jpg",
  },
  {
    id: 16,
    name: "이판사판",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#2,3층으로나눠져있음"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#SeparateFloors(2nd,3rd)"],
    web_link: "https://map.naver.com/p/entry/place/1238323405?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\16이판사판.jpg",
  },
  {
    id: 17,
    name: "닭동가리",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#닭요리 위주", "#행사적합", "#닭발"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#ChickenDishes", "#GoodForEvents", "#ChickenFeet"],
    web_link: "https://map.naver.com/p/entry/place/1699120034?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\17닭동가리.jpg",
  },
  {
    id: 18,
    name: "정육회",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#육회", "#육사시미"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#BeefTartare", "#RawBeefSashimi"],
    web_link: "https://map.naver.com/p/entry/place/2047985103?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\18정육회.jpg",
  },
  {
    id: 19,
    name: "알비노",
    kor_loc: "북문",
    kor_food: ["한식", "양식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기굿"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Fusion"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes"],
    web_link: "https://map.naver.com/p/entry/place/1051677608?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\19알비노.jpg",
  },
  {
    id: 20,
    name: "다원국밥",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#해장용국밥", "#죽고나서가는 곳", "#아침까지술먹기좋음"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#HangoverSoup", "#LastStop", "#DrinkUntilMorning"],
    web_link: "https://map.naver.com/p/entry/place/1380357945?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\20다원국밥.jpg",
  },
  {
    id: 21,
    name: "한신포차",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#닭발"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#ChickenFeet"],
    web_link: "https://map.naver.com/p/entry/place/2060658035?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\21한신포차.jpg",
  },
  {
    id: 22,
    name: "와다다다",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#전집"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#PancakeHouse"],
    web_link: "https://map.naver.com/p/entry/place/1757644998?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\22와다다다.jpg",
  },
  {
    id: 23,
    name: "구르메",
    kor_loc: "북문",
    kor_food: ["한식", "일식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#분위기굿"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Japanese"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#GoodVibes"],
    web_link: "https://map.naver.com/p/entry/place/1771915294?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\23구르메.jpg",
  },
  {
    id: 24,
    name: "역전 할머니 맥주",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식", "중식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#무난함", "#모두가아는술집"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Chinese", "Fusion"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#Basic", "#FamousPub"],
    web_link: "https://map.naver.com/p/entry/place/35629412?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\이미지없음.avif",
  },
  {
    id: 25,
    name: "최군맥주",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [],
    web_link: "https://map.naver.com/p/entry/place/35629412?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\25최군맥주.jpg",
  },
  {
    id: 26,
    name: "더왕365퓨전포차",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [],
    web_link: "https://map.naver.com/p/entry/place/651069155?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\26더왕365퓨전포차.jpg",
  },
  {
    id: 27,
    name: "난탄",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식", "중식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기굿", "#마파두부"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Chinese", "Fusion"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes", "#MapoTofu"],
    web_link: "https://map.naver.com/p/entry/place/2046192198?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\27난탄.jpg",
  },
  {
    id: 28,
    name: "임가양꼬치",
    kor_loc: "북문",
    kor_food: ["중식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#양꼬치"],
    eng_loc: "North Gate",
    eng_food: ["Chinese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#LambSkewers"],
    web_link: "https://map.naver.com/p/entry/place/1045711079?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\28임가양꼬치.jpg",
  },
  {
    id: 29,
    name: "파랑집",
    kor_loc: "북문",
    kor_food: ["중식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#양꼬치"],
    eng_loc: "North Gate",
    eng_food: ["Chinese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#LambSkewers"],
    web_link: "https://map.naver.com/p/entry/place/38378898?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\29파랑집.jpg",
  },
  {
    id: 30,
    name: "better",
    kor_loc: "북문",
    kor_food: ["양식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#생맥주맛집"],
    eng_loc: "North Gate",
    eng_food: ["Western"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#TastyDraftBeer"],
    web_link: "https://map.naver.com/p/entry/place/1036376759?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\a_Noth\\30better.jpg",
  },
  // --- 정문 (Main Gate) ---
  {
    id: 31,
    name: "이유있는 감자탕",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#죽어서가는곳"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#LastStop"],
    web_link: "https://map.naver.com/p/entry/place/1038471458?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\1이유있는 감자탕.jpg",
  },
  {
    id: 32,
    name: "배터지는 깐풍기",
    kor_loc: "정문",
    kor_food: ["한식", "중식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#김피탕맛집"],
    eng_loc: "Main Gate",
    eng_food: ["Korean", "Chinese", "Fusion"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#KimchiPizzaTangsuyuk"],
    web_link: "https://map.naver.com/p/entry/place/1825058903?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\2배터지는 깐풍기.jpg",
  },
  {
    id: 33,
    name: "정문똥집",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#김치찌개맛집"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#TastyKimchiStew"],
    web_link: "https://map.naver.com/p/entry/place/1508542915?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\3정문똥집.jpg",
  },
  {
    id: 34,
    name: "마라도 생굴구이",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#해물탕먹고싶을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#ForSeafoodStew"],
    web_link: "https://map.naver.com/p/entry/place/16133934?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\4마라도 생굴구이.jpg",
  },
  {
    id: 35,
    name: "춘춘갈매기",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#고기먹고싶을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#ForMeat"],
    web_link: "https://map.naver.com/p/entry/place/567693401?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\5춘춘갈매기.jpg",
  },
  {
    id: 36,
    name: "황제뒷고기",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#가성비"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#GoodValue"],
    web_link: "https://map.naver.com/p/entry/place/19617817?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\6황제뒷고기.jpg",
  },
  {
    id: 37,
    name: "족불장군",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: [],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: [],
    web_link: "https://map.naver.com/p/entry/place/1022713177?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\이미지없음.avif",
  },
  {
    id: 38,
    name: "천지삐까리",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#맛있는거천지"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#LotsOfTastyFood"],
    web_link: "https://map.naver.com/p/entry/place/1022713177?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\7천지삐까리.jpg",
  },
  {
    id: 39,
    name: "큰손 왕뼈다귀해장국",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#든든하게술마실때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#HeartyMealAndDrink"],
    web_link: "https://map.naver.com/p/entry/place/449602605?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\8큰손 왕뼈다귀해장국.jpg",
  },
  {
    id: 40,
    name: "꼬지포차",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#제철과일안주나옴"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#SeasonalFruitSnack"],
    web_link: "https://map.naver.com/p/entry/place/38365272?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\이미지없음.avif",
  },
  {
    id: 41,
    name: "낭만상회",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [],
    web_link: "https://map.naver.com/p/entry/place/1162274841?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\이미지없음.avif",
  },
  {
    id: 42,
    name: "경대이모",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#친구랑가기좋음"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#GoodWithFriends"],
    web_link: "https://map.naver.com/p/entry/place/1428840850?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\이미지없음.avif",
  },
  {
    id: 43,
    name: "이웃집",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#뭉티기가먹고싶을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#ForRawBeef"],
    web_link: "https://map.naver.com/p/entry/place/1744477600?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\이미지없음.avif",
  },
  {
    id: 44,
    name: "뼈큰감자탕",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#든든하게술마실때", "#갈곳없을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#HeartyMealAndDrink", "#WhenNoPlaceToGo"],
    web_link: "https://map.naver.com/p/entry/place/13188094?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\13뼈큰감자탕.jpg",
  },
  {
    id: 45,
    name: "만달포차",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#맛있는안주랑술마시고싶을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#TastyFoodAndDrink"],
    web_link: "https://map.naver.com/p/entry/place/1502192494?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\14만달포차.jpg",
  },
  {
    id: 46,
    name: "부자 숯불막창곰장어아나고",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: [],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: [],
    web_link: "https://map.naver.com/p/entry/place/19677149?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\b_Main\\15부자숯불막창곰장어아나고.jpg",
  },

  // --- 쪽문 (Side Gate) ---
  {
    id: 47,
    name: "통큰아저씨",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#회식추천", "#치즈계란말이"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#RecommendedForGroups", "#CheeseEggRoll"],
    web_link: "https://map.naver.com/p/entry/place/1065583558?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\이미지없음.avif",
  },
  {
    id: 48,
    name: "쪽문분식",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#가성비"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#GoodValue"],
    web_link: "https://map.naver.com/p/entry/place/38367700?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\c_Side\\2쪽문분식.jpg",
  },
  {
    id: 49,
    name: "간식여행",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#가성비", "#안주가저렴하고맛있음"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#GoodValue", "#CheapAndTasty"],
    web_link: "https://map.naver.com/p/entry/place/19661483?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\c_Side\\3간식여행.jpg",
  },
  {
    id: 50,
    name: "yin 바",
    kor_loc: "쪽문",
    kor_food: ["양식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기굿", "#다리가짧고귀여운고양이있음"],
    eng_loc: "Side Gate",
    eng_food: ["Western"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes", "#CuteCat"],
    web_link: "https://map.naver.com/p/entry/place/1269237890?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\c_Side\\4yin바.jpg",
  },
  {
    id: 51,
    name: "더 좀비",
    kor_loc: "쪽문",
    kor_food: ["한식", "일식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: [],
    eng_loc: "Side Gate",
    eng_food: ["Korean", "Japanese"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: [],
    web_link: "https://map.naver.com/p/entry/place/2029223476?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\이미지없음.avif",
  },
  {
    id: 52,
    name: "미운 놈 포차",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [],
    web_link: "https://map.naver.com/p/entry/place/1140332547?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\c_Side\\6미운놈포차.jpg",
  },
  {
    id: 53,
    name: "Retro (펍 & 위스키 바)",
    kor_loc: "쪽문",
    kor_food: ["양식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기굿"],
    eng_loc: "Side Gate",
    eng_food: ["Western"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes"],
    web_link: "https://map.naver.com/p/entry/place/1195998994?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\c_Side\\7Retro.jpg",
  },
  {
    id: 54,
    name: "썬더치킨",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: [
      "#대규모인원수용가능",
      "#빔프로젝터있음",
      "#치킨도매우맛있다",
    ],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#LargeGroupsOK", "#BeamProjector", "#TastyChicken"],
    web_link: "https://map.naver.com/p/entry/place/1942043571?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\c_Side\\8썬더치킨.jpg",
},
  {
    id: 55,
    name: "동대구회",
    kor_loc: "쪽문",
    kor_food: ["일식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#맛은있으나여름에매우매우더움"],
    eng_loc: "Side Gate",
    eng_food: ["Japanese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#TastyButHotInSummer"],
    web_link: "https://map.naver.com/p/entry/place/16135779?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\Side\\동대구회.jpg",
  },
  {
    id: 56,
    name: "통큰할매순대국",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#해장술하러가는곳"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#HangoverDrink"],
    web_link: "https://map.naver.com/p/entry/place/1422484329?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\이미지없음.avif",
  },
  {
    id: 57,
    name: "회마을",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#물회맛집"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#TastyRawFishSoup"],
    web_link: "https://map.naver.com/p/entry/place/1182741994?c=15.00,0,0,0,dh",
    img_url: "src\\constant\\img\\c_Side\\11회마을.jpg",
  },
];
export default MOCK_DATA;
