const MOCK_DATA = [
  // --- 북문 (North Gate) ---
  {
    id: 1,
    name: "취향",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식", "중식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#원픽", "#청양크림파스타", "#분위기 좋음"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Chinese", "Fusion"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#MyPick", "#SpicyCreamPasta", "#GoodVibes"],
  },
  {
    id: 2,
    name: "와비사비",
    kor_loc: "북문",
    kor_food: ["일식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#투픽", "#명란크림우동", "#신상술집"],
    eng_loc: "North Gate",
    eng_food: ["Japanese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#2ndPick", "#PollackRoeCreamUdon", "#NewPub"],
  },
  {
    id: 3,
    name: "한라맥주",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#학과행사하기좋음", "#로제찜닭", "#감귤모자", "#넓고좋음"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Fusion"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: [
      "#GoodForEvents",
      "#RoseSteamedChicken",
      "#TangerineHat",
      "#Spacious",
    ],
  },
  {
    id: 4,
    name: "사군자민속촌",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [
      "#낙지볶음에면은한번에섞지말고조금씩섞어먹으세요",
      "#막걸리굿",
      "#빈대떡존맛",
    ],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [
      "#MixNoodlesLittleByLittle",
      "#GoodRiceWine",
      "#TastyMungBeanPancake",
    ],
  },
  {
    id: 5,
    name: "데얼스",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "중식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#어두운 분위기…?", "#기본안주치즈과자", "#떠먹는 피자"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Chinese", "Fusion"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#DarkAtmosphere", "#FreeCheeseSnacks", "#SpoonPizza"],
  },
  {
    id: 6,
    name: "오뉴월",
    kor_loc: "북문",
    kor_food: ["일식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기 좋음", "#이자카야느낌"],
    eng_loc: "North Gate",
    eng_food: ["Japanese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes", "#IzakayaStyle"],
  },
  {
    id: 7,
    name: "사심",
    kor_loc: "북문",
    kor_food: ["일식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기 좋음", "#이자카야 느낌", "#야끼소바"],
    eng_loc: "North Gate",
    eng_food: ["Japanese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes", "#IzakayaStyle", "#Yakisoba"],
  },
  {
    id: 8,
    name: "희희",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#과 행사하기 좋음", "#샤브샤브", "#기본안주 맛있음"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Fusion"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#GoodForEvents", "#ShabuShabu", "#TastyFreeSnacks"],
  },
  {
    id: 9,
    name: "구구포차",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#야구보기 좋음", "#과 행사하기 좋음", "#닭요리 위주"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#GoodForBaseball", "#GoodForEvents", "#ChickenDishes"],
  },
  {
    id: 10,
    name: "정든밤",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#안주가 다 맛있는 편", "#10인 단체도 가능", "#분위기굿"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#TastyDishes", "#GroupsOf10OK", "#GoodVibes"],
  },
  {
    id: 11,
    name: "정선생",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#고구마크림막걸리", "#분위기굿"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#SweetPotatoCreamRiceWine", "#GoodVibes"],
  },
  {
    id: 12,
    name: "큐브",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "과팅"],
    kor_hashtag: ["#룸술집"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Group Dating"],
    eng_hashtag: ["#PrivateRoom"],
  },
  {
    id: 13,
    name: "청춘",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "과팅"],
    kor_hashtag: ["#룸술집"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Group Dating"],
    eng_hashtag: ["#PrivateRoom"],
  },
  {
    id: 14,
    name: "사랑과평화",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#계수작반반양념구이", "#행사적합", "#스크린이랑마이크있음"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Fusion"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#HalfHalfSeasonedGrill", "#GoodForEvents", "#ScreenAndMic"],
  },
  {
    id: 15,
    name: "홍등연화",
    kor_loc: "북문",
    kor_food: ["한식", "일식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#지하", "#행사적합"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Japanese", "Fusion"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#Basement", "#GoodForEvents"],
  },
  {
    id: 16,
    name: "이판사판",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#2,3층으로나눠져있음"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#SeparateFloors(2nd,3rd)"],
  },
  {
    id: 17,
    name: "닭동가리",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#닭요리 위주", "#행사적합", "#닭발"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#ChickenDishes", "#GoodForEvents", "#ChickenFeet"],
  },
  {
    id: 18,
    name: "정육회",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#육회", "#육사시미"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#BeefTartare", "#RawBeefSashimi"],
  },
  {
    id: 19,
    name: "알비노",
    kor_loc: "북문",
    kor_food: ["한식", "양식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기굿"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Fusion"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes"],
  },
  {
    id: 20,
    name: "다원국밥",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#해장용국밥", "#죽고나서가는 곳", "#아침까지술먹기좋음"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#HangoverSoup", "#LastStop", "#DrinkUntilMorning"],
  },
  {
    id: 21,
    name: "한신포차",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#닭발"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#ChickenFeet"],
  },
  {
    id: 22,
    name: "와다다다",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#전집"],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#PancakeHouse"],
  },
  {
    id: 23,
    name: "구르메",
    kor_loc: "북문",
    kor_food: ["한식", "일식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#분위기굿"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Japanese"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#GoodVibes"],
  },
  {
    id: 24,
    name: "역전 할머니 맥주",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식", "중식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#무난함", "#모두가아는술집"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Chinese", "Fusion"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#Basic", "#FamousPub"],
  },
  {
    id: 25,
    name: "최군맥주",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [],
  },
  {
    id: 26,
    name: "더왕365퓨전포차",
    kor_loc: "북문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [],
    eng_loc: "North Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [],
  },
  {
    id: 27,
    name: "난탄",
    kor_loc: "북문",
    kor_food: ["한식", "양식", "일식", "중식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기굿", "#마파두부"],
    eng_loc: "North Gate",
    eng_food: ["Korean", "Western", "Japanese", "Chinese", "Fusion"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes", "#MapoTofu"],
  },
  {
    id: 28,
    name: "임가양꼬치",
    kor_loc: "북문",
    kor_food: ["중식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#양꼬치"],
    eng_loc: "North Gate",
    eng_food: ["Chinese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#LambSkewers"],
  },
  {
    id: 29,
    name: "파랑집",
    kor_loc: "북문",
    kor_food: ["중식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#양꼬치"],
    eng_loc: "North Gate",
    eng_food: ["Chinese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#LambSkewers"],
  },
  {
    id: 30,
    name: "better",
    kor_loc: "북문",
    kor_food: ["양식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#생맥주맛집"],
    eng_loc: "North Gate",
    eng_food: ["Western"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#TastyDraftBeer"],
  },
  // --- 정문 (Main Gate) ---
  {
    id: 31,
    name: "이유있는 감자탕",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#죽어서가는곳"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#LastStop"],
  },
  {
    id: 32,
    name: "배터지는 깐풍기",
    kor_loc: "정문",
    kor_food: ["한식", "중식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#김피탕맛집"],
    eng_loc: "Main Gate",
    eng_food: ["Korean", "Chinese", "Fusion"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#KimchiPizzaTangsuyuk"],
  },
  {
    id: 33,
    name: "정문똥집",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#김치찌개맛집"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#TastyKimchiStew"],
  },
  {
    id: 34,
    name: "마라도 생굴구이",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#해물탕먹고싶을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#ForSeafoodStew"],
  },
  {
    id: 35,
    name: "춘춘갈매기",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#고기먹고싶을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#ForMeat"],
  },
  {
    id: 36,
    name: "황제뒷고기",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#가성비"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#GoodValue"],
  },
  {
    id: 37,
    name: "족불장군",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: [],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: [],
  },
  {
    id: 38,
    name: "천지삐까리",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#맛있는거천지"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#LotsOfTastyFood"],
  },
  {
    id: 39,
    name: "큰손 왕뼈다귀해장국",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#든든하게술마실때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#HeartyMealAndDrink"],
  },
  {
    id: 40,
    name: "꼬지포차",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#제철과일안주나옴"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#SeasonalFruitSnack"],
  },
  {
    id: 41,
    name: "낭만상회",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [],
  },
  {
    id: 42,
    name: "경대이모",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#친구랑가기좋음"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#GoodWithFriends"],
  },
  {
    id: 43,
    name: "이웃집",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#뭉티기가먹고싶을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#ForRawBeef"],
  },
  {
    id: 44,
    name: "뼈큰감자탕",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#든든하게술마실때", "#갈곳없을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#HeartyMealAndDrink", "#WhenNoPlaceToGo"],
  },
  {
    id: 45,
    name: "만달포차",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인", "커플"],
    kor_hashtag: ["#맛있는안주랑술마시고싶을때"],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends", "Couples"],
    eng_hashtag: ["#TastyFoodAndDrink"],
  },
  {
    id: 46,
    name: "부자 숯불막창곰장어아나고",
    kor_loc: "정문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: [],
    eng_loc: "Main Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: [],
  },
  // --- 쪽문 (Side Gate) ---
  {
    id: 47,
    name: "통큰아저씨",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: ["#회식추천", "#치즈계란말이"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#RecommendedForGroups", "#CheeseEggRoll"],
  },
  {
    id: 48,
    name: "쪽문분식",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#가성비"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#GoodValue"],
  },
  {
    id: 49,
    name: "간식여행",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#가성비", "#안주가저렴하고맛있음"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#GoodValue", "#CheapAndTasty"],
  },
  {
    id: 50,
    name: "yin 바",
    kor_loc: "쪽문",
    kor_food: ["양식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기굿", "#다리가짧고귀여운고양이있음"],
    eng_loc: "Side Gate",
    eng_food: ["Western"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes", "#CuteCat"],
  },
  {
    id: 51,
    name: "더 좀비",
    kor_loc: "쪽문",
    kor_food: ["한식", "일식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: [],
    eng_loc: "Side Gate",
    eng_food: ["Korean", "Japanese"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: [],
  },
  {
    id: 52,
    name: "미운 놈 포차",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: [],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: [],
  },
  {
    id: 53,
    name: "Retro (펍 & 위스키 바)",
    kor_loc: "쪽문",
    kor_food: ["양식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#분위기굿"],
    eng_loc: "Side Gate",
    eng_food: ["Western"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#GoodVibes"],
  },
  {
    id: 54,
    name: "썬더치킨",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["회식", "지인"],
    kor_hashtag: [
      "#대규모인원수용가능",
      "#빔프로젝터있음",
      "#치킨도매우맛있다",
    ],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Groups", "Friends"],
    eng_hashtag: ["#LargeGroupsOK", "#BeamProjector", "#TastyChicken"],
  },
  {
    id: 55,
    name: "동대구회",
    kor_loc: "쪽문",
    kor_food: ["일식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#맛은있으나여름에매우매우더움"],
    eng_loc: "Side Gate",
    eng_food: ["Japanese"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#TastyButHotInSummer"],
  },
  {
    id: 56,
    name: "통큰할매순대국",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인"],
    kor_hashtag: ["#해장술하러가는곳"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends"],
    eng_hashtag: ["#HangoverDrink"],
  },
  {
    id: 57,
    name: "회마을",
    kor_loc: "쪽문",
    kor_food: ["한식"],
    kor_mood: ["지인", "커플"],
    kor_hashtag: ["#물회맛집"],
    eng_loc: "Side Gate",
    eng_food: ["Korean"],
    eng_mood: ["Friends", "Couples"],
    eng_hashtag: ["#TastyRawFishSoup"],
  },
];
export default MOCK_DATA;
